# Montréal à vélo

From the city of Montreal Open Data sources, I want to look at the relationship between bike paths, bike accidents, bike traffic. 
http://donnees.ville.montreal.qc.ca/dataset?q=v%C3%A9lo

Create a heatmap of bike accidents, per year.

In [221]:
import pandas as pd
pd.set_option('display.max_columns', None) # Display all the columns
import numpy as np

In [222]:
# Data path
path = "/Users/julien/Documents/DATA/MTL-a-velo/"

# Collisions routières

In [223]:
df = pd.read_csv(path+"collisions_routieres/collisions_routieres.csv",skipinitialspace=True)

In [224]:
df.head()

,NO_SEQ_COLL,JR_SEMN_ACCDN,DT_ACCDN,CD_MUNCP,NO_CIVIQ_ACCDN,SFX_NO_CIVIQ_ACCDN,BORNE_KM_ACCDN,RUE_ACCDN,TP_REPRR_ACCDN,ACCDN_PRES_DE,NB_METRE_DIST_ACCD,CD_GENRE_ACCDN,CD_SIT_PRTCE_ACCDN,CD_ETAT_SURFC,CD_ECLRM,CD_ENVRN_ACCDN,NO_ROUTE,CD_CATEG_ROUTE,CD_ETAT_CHASS,CD_ASPCT_ROUTE,CD_LOCLN_ACCDN,CD_POSI_ACCDN,CD_CONFG_ROUTE,CD_ZON_TRAVX_ROUTR,CD_PNT_CDRNL_ROUTE,CD_PNT_CDRNL_REPRR,CD_COND_METEO,NB_VEH_IMPLIQUES_ACCDN,NB_MORTS,NB_BLESSES_GRAVES,NB_BLESSES_LEGERS,HEURE_ACCDN,AN,NB_VICTIMES_TOTAL,GRAVITE,REG_ADM,MRC,nb_automobile_camion_leger,nb_camionLourd_tractRoutier,nb_outil_equipement,nb_tous_autobus_minibus,nb_bicyclette,nb_cyclomoteur,nb_motocyclette,nb_taxi,nb_urgence,nb_motoneige,nb_VHR,nb_autres_types,nb_veh_non_precise,NB_DECES_PIETON,NB_BLESSES_PIETON,NB_VICTIMES_PIETON,NB_DECES_MOTO,NB_BLESSES_MOTO,NB_VICTIMES_MOTO,NB_DECES_VELO,NB_BLESSES_VELO,NB_VICTIMES_VELO,VITESSE_AUTOR,LOC_X,LOC_Y,LOC_COTE_QD,LOC_COTE_PD,LOC_DETACHEE,LOC_IMPRECISION,LOC_LAT,LOC_LONG
0,SPVM _ 2012 _ 1,ME,2012/02/01,66102.0,3501.0,NaN,NaN,ST CHARLES,2.0,STAT,NaN,31.0,NaN,16.0,1.0,1.0,NaN,21.0,NaN,11.0,33.0,NaN,4.0,NaN,NaN,NaN,11.0,2,0,0,0,Non précisé,2012,0,Dommages matériels inférieurs au seuil de rapp...,Montréal(06),Montréal (66 ),1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,NaN,276517.37950,5.035127e+06,A,3,O,N,45.45550,-73.86162
1,SPVM _ 2012 _ 2,SA,2012/06/02,66023.0,NaN,NaN,NaN,NaN,NaN,COTE VERTU ET AUT 40,NaN,59.0,NaN,11.0,1.0,3.0,NaN,11.0,NaN,22.0,37.0,NaN,1.0,NaN,NaN,NaN,11.0,1,0,0,0,15:00:00-15:59:00,2012,0,Dommages matériels seulement,Montréal(06),Montréal (66 ),1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,287913.26000,5.038666e+06,A,3,N,O,45.48772,-73.71603
2,SPVM _ 2012 _ 3,JE,2012/06/28,66023.0,NaN,NaN,NaN,COTE VERTU,1.0,DECARIE,NaN,31.0,NaN,11.0,1.0,3.0,NaN,13.0,NaN,11.0,32.0,NaN,3.0,NaN,NaN,O,11.0,2,0,0,0,08:00:00-08:59:00,2012,0,Dommages matériels inférieurs au seuil de rapp...,Montréal(06),Montréal (66 ),1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,50.0,290518.82501,5.041617e+06,A,1,N,N,45.51432,-73.68279
3,SPVM _ 2012 _ 4,ME,2012/07/11,66023.0,NaN,NaN,NaN,ST MATHIEU,1.0,RENE LEVESQUE,50.0,31.0,NaN,11.0,3.0,3.0,NaN,13.0,NaN,11.0,33.0,NaN,2.0,NaN,NaN,NaN,11.0,2,0,0,0,09:00:00-09:59:00,2012,0,Dommages matériels inférieurs au seuil de rapp...,Montréal(06),Montréal (66 ),1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,50.0,298822.88600,5.039146e+06,A,3,N,N,45.49221,-73.57647
4,SPVM _ 2012 _ 5,LU,2012/01/02,66023.0,4849.0,NaN,NaN,ST JEAN,NaN,NaN,NaN,31.0,NaN,12.0,1.0,3.0,NaN,21.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,2,0,0,0,Non précisé,2012,0,Dommages matériels seulement,Montréal(06),Montréal (66 ),1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,NaN,277433.35738,5.038881e+06,A,1,O,N,45.48932,-73.85011

In [225]:
# print(df.shape)
# print(df.dtypes)
# print(df.info())
# #print(df.describe())

In [226]:
# Keep only related columns

df = df[['DT_ACCDN','JR_SEMN_ACCDN','HEURE_ACCDN','REG_ADM','VITESSE_AUTOR','CD_GENRE_ACCDN','CD_ETAT_SURFC','CD_ECLRM','CD_CONFG_ROUTE','CD_COND_METEO','LOC_LAT','LOC_LONG','NB_DECES_VELO','NB_BLESSES_VELO','NB_VICTIMES_VELO']]
df

,DT_ACCDN,JR_SEMN_ACCDN,HEURE_ACCDN,REG_ADM,VITESSE_AUTOR,CD_GENRE_ACCDN,CD_ETAT_SURFC,CD_ECLRM,CD_CONFG_ROUTE,CD_COND_METEO,LOC_LAT,LOC_LONG,NB_DECES_VELO,NB_BLESSES_VELO,NB_VICTIMES_VELO
0,2012/02/01,ME,Non précisé,Montréal(06),NaN,31.0,16.0,1.0,4.0,11.0,45.45550,-73.86162,0,0,0
1,2012/06/02,SA,15:00:00-15:59:00,Montréal(06),NaN,59.0,11.0,1.0,1.0,11.0,45.48772,-73.71603,0,0,0
2,2012/06/28,JE,08:00:00-08:59:00,Montréal(06),50.0,31.0,11.0,1.0,3.0,11.0,45.51432,-73.68279,0,0,0
3,2012/07/11,ME,09:00:00-09:59:00,Montréal(06),50.0,31.0,11.0,3.0,2.0,11.0,45.49221,-73.57647,0,0,0
4,2012/01/02,LU,Non précisé,Montréal(06),NaN,31.0,12.0,1.0,NaN,11.0,45.48932,-73.85011,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190547,2019/12/18,ME,06:00:00-06:59:00,Montréal(06),NaN,31.0,12.0,2.0,3.0,17.0,45.43229,-73.90425,0,0,0
190548,2019/12/18,ME,Non précisé,Montréal(06),50.0,31.0,16.0,3.0,3.0,17.0,45.45162,-73.85785,0,0,0
190549,2019/12/19,JE,10:00:00-10:59:00,Montréal(06),NaN,32.0,11.0,1.0,9.0,11.0,45.43989,-73.88605,0,0,0
190550,2019/12/27,VE,13:00:00-13:59:00,Montréal(06),40.0,42.0,18.0,2.0,2.0,19.0,45.41600,-73.88040,0,0,0
190551,2019/12/31,MA,14:00:00-14:59:00,Montréal(06),50.0,42.0,12.0,1.0,1.0,NaN,45.44495,-73.87516,0,0,0

In [227]:
# Keep only related rows
df = df[(df['NB_DECES_VELO'] == 1) | (df['NB_BLESSES_VELO'] == 1) | (df['NB_VICTIMES_VELO'] == 1)].copy()

In [228]:
df.HEURE_ACCDN.value_counts()

16:00:00-16:59:00    557
17:00:00-17:59:00    550
15:00:00-15:59:00    429
18:00:00-18:59:00    399
08:00:00-08:59:00    392
12:00:00-12:59:00    290
14:00:00-14:59:00    288
09:00:00-09:59:00    283
13:00:00-13:59:00    275
19:00:00-19:59:00    243
07:00:00-07:59:00    236
11:00:00-11:59:00    221
10:00:00-10:59:00    221
20:00:00-20:59:00    207
21:00:00-21:59:00    191
22:00:00-22:59:00    124
Non précisé          108
23:00:00-23:59:00    104
06:00:00-06:59:00     85
00:00:00-00:59:00     80
03:00:00-03:59:00     52
01:00:00-01:59:00     47
02:00:00-02:59:00     26
05:00:00-05:59:00     25
04:00:00-04:59:00     22
Name: HEURE_ACCDN, dtype: int64

In [229]:
# Create features : year, month, day, hour,  Daytime - Nighttime. 


# Convert to datetime
df.DT_ACCDN = pd.to_datetime(df.DT_ACCDN, format='%Y-%m-%d', errors='coerce')
df['HEURE_ACCDN'] = [x[0:5] for x in df['HEURE_ACCDN']]
df['HEURE_ACCDN'] = df['HEURE_ACCDN'].replace('NA',)
df

,DT_ACCDN,JR_SEMN_ACCDN,HEURE_ACCDN,REG_ADM,VITESSE_AUTOR,CD_GENRE_ACCDN,CD_ETAT_SURFC,CD_ECLRM,CD_CONFG_ROUTE,CD_COND_METEO,LOC_LAT,LOC_LONG,NB_DECES_VELO,NB_BLESSES_VELO,NB_VICTIMES_VELO
143,2012-03-18,DI,15:00,Montréal(06),50.0,33.0,11.0,1.0,2.0,11.0,45.50579,-73.77561,0,1,1
210,2012-04-19,JE,17:00,Montréal(06),50.0,33.0,11.0,NaN,2.0,11.0,45.50068,-73.84722,0,1,1
212,2012-04-26,JE,00:00,Montréal(06),50.0,33.0,11.0,3.0,4.0,11.0,45.50203,-73.81524,0,1,1
264,2012-05-26,SA,13:00,Montréal(06),50.0,33.0,11.0,1.0,3.0,11.0,45.50205,-73.83469,0,1,1
271,2012-05-30,ME,11:00,Montréal(06),50.0,33.0,11.0,1.0,3.0,11.0,45.50404,-73.82734,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190466,2019-09-01,DI,14:00,Montréal(06),30.0,33.0,11.0,1.0,1.0,11.0,45.41519,-73.89064,0,1,1
190474,2019-09-17,MA,11:00,Montréal(06),NaN,33.0,11.0,1.0,4.0,11.0,45.45937,-73.86525,0,1,1
190497,2019-10-11,VE,15:00,Montréal(06),30.0,33.0,11.0,1.0,2.0,11.0,45.42695,-73.85697,0,1,1
190499,2019-10-13,DI,15:00,Montréal(06),50.0,33.0,11.0,1.0,5.0,11.0,45.45788,-73.86395,0,1,1
190535,2019-12-03,MA,14:00,Montréal(06),NaN,33.0,11.0,1.0,2.0,11.0,45.40329,-73.94172,0,1,1

In [230]:
#df['hour'] = pd.to_datetime(df.HEURE_ACCDN,format= '%H:%M').dt.hour

# df['month'] = df['DT_ACCDN'].month
# df['week-day'] = df['DT_ACCDN'].weekday

In [231]:
# df['year'] = pd.DatetimeIndex(pd.to_datetime(df['year'],format= '%Y').dt.year).year
# df['year'] = 

# df['month'] = pd.DatetimeIndex(df['DT_ACCDN']).month
# df['week-day'] = pd.DatetimeIndex(df['DT_ACCDN']).weekday

# df.head()

In [232]:
df['year'] = pd.DatetimeIndex(df['DT_ACCDN']).year
df['month'] = pd.DatetimeIndex(df['DT_ACCDN']).month
df['week-day'] = pd.DatetimeIndex(df['DT_ACCDN']).weekday

df.head()

,DT_ACCDN,JR_SEMN_ACCDN,HEURE_ACCDN,REG_ADM,VITESSE_AUTOR,CD_GENRE_ACCDN,CD_ETAT_SURFC,CD_ECLRM,CD_CONFG_ROUTE,CD_COND_METEO,LOC_LAT,LOC_LONG,NB_DECES_VELO,NB_BLESSES_VELO,NB_VICTIMES_VELO,year,month,week-day
143,2012-03-18,DI,15:00,Montréal(06),50.0,33.0,11.0,1.0,2.0,11.0,45.50579,-73.77561,0,1,1,2012,3,6
210,2012-04-19,JE,17:00,Montréal(06),50.0,33.0,11.0,NaN,2.0,11.0,45.50068,-73.84722,0,1,1,2012,4,3
212,2012-04-26,JE,00:00,Montréal(06),50.0,33.0,11.0,3.0,4.0,11.0,45.50203,-73.81524,0,1,1,2012,4,3
264,2012-05-26,SA,13:00,Montréal(06),50.0,33.0,11.0,1.0,3.0,11.0,45.50205,-73.83469,0,1,1,2012,5,5
271,2012-05-30,ME,11:00,Montréal(06),50.0,33.0,11.0,1.0,3.0,11.0,45.50404,-73.82734,0,1,1,2012,5,2

In [235]:
# Building the map
# Load an empty map
from keplergl import KeplerGl
map_1 = KeplerGl()
map_1

User Guide: https://docs.kepler.gl/docs/keplergl-jupyter

KeplerGl()

In [236]:
map_1.add_data(data=df, name='velo')

In [239]:
config = {
  "version": "v1",
  "config": {
    "visState": {
      "filters": [
        {
          "dataId": [
            "velo"
          ],
          "id": "o9fnm9kdg",
          "name": [
            "DT_ACCDN"
          ],
          "type": "timeRange",
          "value": [
            1326067200000,
            1577750400000
          ],
          "enlarged": True,
          "plotType": "histogram",
          "yAxis": None
        },
        {
          "dataId": [
            "velo"
          ],
          "id": "tofracjvk",
          "name": [
            "year"
          ],
          "type": "range",
          "value": [
            2012,
            2019
          ],
          "enlarged": False,
          "plotType": "histogram",
          "yAxis": None
        }
      ],
      "layers": [
        {
          "id": "wl56th8",
          "type": "heatmap",
          "config": {
            "dataId": "velo",
            "label": "new layer",
            "color": [
              218,
              112,
              191
            ],
            "columns": {
              "lat": "LOC_LAT",
              "lng": "LOC_LONG"
            },
            "isVisible": True,
            "visConfig": {
              "opacity": 0.8,
              "colorRange": {
                "name": "Global Warming",
                "type": "sequential",
                "category": "Uber",
                "colors": [
                  "#5A1846",
                  "#900C3F",
                  "#C70039",
                  "#E3611C",
                  "#F1920E",
                  "#FFC300"
                ]
              },
              "radius": 20
            },
            "hidden": False,
            "textLabel": [
              {
                "field": None,
                "color": [
                  255,
                  255,
                  255
                ],
                "size": 18,
                "offset": [
                  0,
                  0
                ],
                "anchor": "start",
                "alignment": "center"
              }
            ]
          },
          "visualChannels": {
            "weightField": None,
            "weightScale": "linear"
          }
        }
      ],
      "interactionConfig": {
        "tooltip": {
          "fieldsToShow": {
            "velo": [
              {
                "name": "DT_ACCDN",
                "format": None
              },
              {
                "name": "JR_SEMN_ACCDN",
                "format": None
              },
              {
                "name": "HEURE_ACCDN",
                "format": None
              },
              {
                "name": "REG_ADM",
                "format": None
              },
              {
                "name": "VITESSE_AUTOR",
                "format": None
              }
            ]
          },
          "compareMode": False,
          "compareType": "absolute",
          "enabled": True
        },
        "brush": {
          "size": 0.5,
          "enabled": False
        },
        "geocoder": {
          "enabled": False
        },
        "coordinate": {
          "enabled": False
        }
      },
      "layerBlending": "normal",
      "splitMaps": [],
      "animationConfig": {
        "currentTime": None,
        "speed": 1
      }
    },
    "mapState": {
      "bearing": 24,
      "dragRotate": True,
      "latitude": 45.48739050485342,
      "longitude": -73.78936445599886,
      "pitch": 50,
      "zoom": 10.178348447116203,
      "isSplit": False
    },
    "mapStyle": {
      "styleType": "dark",
      "topLayerGroups": {},
      "visibleLayerGroups": {
        "label": True,
        "road": True,
        "border": False,
        "building": True,
        "water": True,
        "land": True,
        "3d building": False
      },
      "threeDBuildingColor": [
        9.665468314072013,
        17.18305478057247,
        31.1442867897876
      ],
      "mapStyles": {}
    }
  }
}

In [240]:
map_1.config = config

In [241]:
map_1

KeplerGl(config={'version': 'v1', 'config': {'visState': {'filters': [{'dataId': ['velo'], 'id': 'o9fnm9kdg', …

In [243]:
map_1.save_to_html(data={'velo': df}, config=config, file_name='first_map.html')

TypeError: Object of type Timestamp is not JSON serializable

In [ ]:
total = df.isnull().sum().sort_values(ascending=False)
percent = (df.isnull().sum()/df.isnull().count()).sort_values(ascending=False)
missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_data